application: threedator
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:

- url: /ships.*
  script: ships.app
  secure: always

- url: /hit.*
  script: hit.app
  secure: always

- url: .*
  script: main.app
  secure: always

libraries:
- name: webapp2
  version: latest
- name: pycrypto
  version: latest
- name: jinja2
  version: latest
